### ISSUE TITLE
Problem with the login

### ISSUE THREAD

**Issue by Marcellux02** [chemokita13/beReal-api#1]
I created an app that allows other people to download bereals. 
Using the same backend to login, UK users with prefix +44 are unable to do so. I get the following error:
{'error': {'code': 400, 'message': 'APP_NOT_VERIFIED', 'errors': [{'message': 'APP_NOT_VERIFIED', 'domain': 'global', 'reason': 'invalid'}]}}

Does anyone have a solution or has faced this problem already?

**Comment by chemokita13** [comment]
Hey! Let me some time to investigate that, I think its because some countries are using other method to login

**Comment by Marcellux02** [comment]
Ok thanks :)

**Comment by Marcellux02** [comment]
@chemokita13 No problem, I fixed the bug. I've simply used another endpoint when the first one doesn't work.
