### ISSUE TITLE
can I get own post history?

### ISSUE THREAD

**Issue by RomanBrodetski** [chemokita13/beReal-api#13]
In the app one can see own history, but I don't see such an endpoint in swagger. Is it supported? Thanks!

**Comment by chemokita13** [comment]
Actualy, that feature is not availible, but let me some time to add it!

**Comment by chemokita13** [comment]
Hey! Try it on https://berealapi.fly.dev/api#/Friends/FriendsController_GetMemFeed ! And tell me if all is ok
