### ISSUE TITLE
Friends list

### ISSUE THREAD

**Issue by Marcellux02** [chemokita13/beReal-api#2]
When I make the api call to the "relationships/friends" endpoint I get a response that it has the correct number of friends but I only get 50 users and not the actual number. Below is an example response:

{'next': '0eHV2jH................lGHP2', 'total': 53, 'data': []}
In data i recieve 50 keys and not 53

**Comment by chemokita13** [comment]
Hey! BeReal API actually is showing responses limited. To show the "second part" of your friends you have to use the **next** param as a url param called **page**.
```bash 
[url]/relationships/friends?page=<nextToken>
```

**Comment by Marcellux02** [comment]
@chemokita13 do you know:
if I have less than 50 friends, the "next" field isn't there, right?

if i have more than 100 friends, does the "next" field return an array of pages or what?

**Comment by chemokita13** [comment]
For each route as far I know there is a limit, in that route, the limit is 50, that means if you have 101 friends you will have to do 3 requests, 1 for the first 50 friends, secon with the second 50 friends and the third with that last friend.
I let you a piece of code on that repo that catch all the posts of friends-of-friends posts using the next token:
```javascript
// It makes the request
let respone = await bf.getFriendsOfFriendsFeed();
// Catch the first 10 posts
let feed = [...respone.data.data];
while (respone.data.next) {
     // Make the secondary responses using "next" param
     respone = await bf.getFriendsOfFriendsFeed(respone.data.next);
     // catch the other feeds
     feed = [...feed, ...respone.data.data];
     }
```

**Comment by Marcellux02** [comment]
Thanks, now it's all clear
