### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by black-alpha-labs** [chemokita13/beReal-api#25]
I have an issue even accessing the localhost. I have successfully deployed as you can see in the image below. However when trying to access localhost:3000 I get a 404 Not Found error ({"statusCode":404,"message":"Cannot GET /","error":"Not Found"}). 
This happens both on my laptop and desktop. Have I missed something?

![Screenshot 2024-01-12 214925](https://github.com/chemokita13/beReal-api/assets/82902572/181bb66c-754a-4b9c-beee-582302a3641c)

**Comment by chemokita13** [comment]
Hey! Because the API has no index page, you should go to the API Docs page (http://localhost:3000/api) or use the rest of the API endpoints

**Comment by black-alpha-labs** [comment]
Thank you. Got it to work
