### ISSUE TITLE
internal server error on /post and /friends

### ISSUE THREAD

**Issue by black-alpha-labs** [chemokita13/beReal-api#28]
I guess BeReal just changed some endpoints as none of the "Friends" and "Post" GET functions work for me anymore. Yesterday everything still worked fine but starting today I keep getting 500 internal server error with my valid token. 
However login functions an ping server still work.

**Comment by black-alpha-labs** [comment]
Yes I am sure. I have just tested it again with a freshly send opt code to my smarthphone. I can verify that opt code and get a valid token. Refreshing this particular token works as well. 
Exectuting any of the GET functions also don't return "malformed jwt token" or "Token not generated" but:
{
  "status": 500,
  "message": "Internal server error",
  "data": {
    "message": "Request failed with status code 400",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 400\n    at settle (/app/node_modules/axios/dist/node/axios.cjs:1970:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3069:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.6.5",
        "Content-Length": "285",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
      "url": "https://auth.bereal.team/api/vonage/check-code",
      "data": "{\"vonageRequestId\":\"AD8T5Iu8Qthai92Ri5AJ0YmTLvOEQpuA9vramp6AqBJr64xcLTh2MNsOX9IHu644sO0_laROnGm5fwFZS6HmdLHjA1LL8ZX0COINdF5dqDhqCMai45ijwM2CppzFAdBwoh3l_0akScR_IdsTn5WK78AgvM6dwquLAi8mF_cSa2DM8zAB_IcHHASa4x-Y_W0dkJrbOJ6cjvux0Kpt-CmdzPNhLH0r6hPrB2Ui-hcuQFh51PMZr62TVM8\",\"code\":\"254600\"}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 400
  }
}

**Comment by chemokita13** [comment]
I will work on it!

**Comment by 083noah** [comment]
> I will work on it!

Do you already know when you will be finished? I really need to see this today, I think it expires tomorrow between 11 a.m. and 5 p.m

It would be WONDERFUL if you made it that far!!!

**Comment by chemokita13** [comment]
I don't know, I am a student in an exams week and Im not sure when I am having time for coding

**Comment by 083noah** [comment]
> I don't know, I am a student in an exams week and Im not sure when I am having time for coding

oh okay, good luck! 
would be great if you can do it in next time! :)

**Comment by chemokita13** [comment]
@083noah  Solved!
