### ISSUE TITLE
Internal server error on /post and /friends again

### ISSUE THREAD

**Issue by black-alpha-labs** [chemokita13/beReal-api#31]
I guess BeReal has just changed some endpoints again as none of the "Friends" and "Post" GET functions work for me anymore. Starting today I keep getting 500 internal server error with my valid token.
However login functions and ping server still work (just like last month when it broke).

Executing any GET functions returns:
{
  "status": 500,
  "message": "Internal server error",
  "data": {
    "message": "Request failed with status code 401",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 401\n    at settle (/app/node_modules/axios/dist/node/axios.cjs:1967:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3066:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/app/node_modules/axios/dist/node/axios.cjs:3877:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BeFake._apiRequest (/app/dist/BeFake/BeFake.js:349:26)\n    at async BeFake.getFriendsFeed (/app/dist/BeFake/BeFake.js:364:26)\n    at async FriendsService.getFeed (/app/dist/friends/friends.service.js:31:26)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Authorization": "Bearer... (token replaced)",
        "bereal-app-version-code": "14549",
        "bereal-signature": "berealsignature",
        "bereal-device-id": "berealdeviceid",
        "User-Agent": "axios/1.6.7",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "get",
      "url": "https://mobile.bereal.com/api/feeds/friends-v1"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 401
  }

**Comment by basti394** [comment]
same for me here. I checked if add the token correctly to the header and I did. So there is a problem on api side
