### ISSUE TITLE
/login/send-code returns 201 although BeReal returns 400

### ISSUE THREAD

**Issue by basti394** [chemokita13/beReal-api#41]
Apparently I tried to login too many times. So BeReal returns 400 as error, but your API returns 201.
This is the JSON returned by your API:
`{"status":201,"message":"OTP sent","data":{"otpSession":{"error":{"code":400,"message":"TOO_MANY_ATTEMPTS_TRY_LATER","errors":[{"message":"TOO_MANY_ATTEMPTS_TRY_LATER","domain":"global","reason":"invalid"}]}}}}`

**Comment by y4aniv** [comment]
I am making a patch that I will submit.
